
const LOADING = 'LOADING';
const SET_SORTING_METHOD = 'SET_SORTING_METHOD';
const TICKETS_ERROR = 'TICKETS_ERROR';
const TICKETS_LOADED = 'TICKETS_LOADED';
const TOGGLE_FILTER = 'TOGGLE_FILTER';
const TOGGLE_FILTER_VIEW = 'TOGGLE_FILTER_VIEW';

export {
  LOADING,
  SET_SORTING_METHOD,
  TICKETS_ERROR,
  TICKETS_LOADED,
  TOGGLE_FILTER,
  TOGGLE_FILTER_VIEW,
}
