const ALL_TICKETS_LOADED = 'ALL_TICKETS_LOADED';
const SET_SORTING_METHOD = 'SET_SORTING_METHOD';
const TICKETS_ERROR = 'TICKETS_ERROR';
const TOGGLE_FILTER = 'TOGGLE_FILTER';
const TOGGLE_FILTER_VIEW = 'TOGGLE_FILTER_VIEW';
const TICKETS_SET_LOADED = 'TICKETS_SET_LOADED';

export {
  ALL_TICKETS_LOADED,
  SET_SORTING_METHOD,
  TICKETS_ERROR,
  TOGGLE_FILTER,
  TOGGLE_FILTER_VIEW,
  TICKETS_SET_LOADED,
};
